import { PageHeader, Card, Badge, Button } from "@floodwatch/ui";

interface Report {
  id: string;
  title: string;
  type: string;
  period: string;
  status: "ready" | "scheduled" | "generating";
  size: string;
}

const REPORTS: Report[] = [
  { id: "RPT-2026-031", title: "Daily national risk briefing", type: "Daily", period: "2026-08-04", status: "ready", size: "1.2 MB" },
  { id: "RPT-2026-030", title: "Weekly situational report — W31", type: "Weekly", period: "2026-07-28 — 08-03", status: "ready", size: "4.8 MB" },
  { id: "RPT-2026-029", title: "County flash report — Tana River", type: "On-demand", period: "2026-08-03", status: "ready", size: "0.9 MB" },
  { id: "RPT-2026-028", title: "Model validation report — Q2", type: "Quarterly", period: "2026 Q2", status: "ready", size: "11.3 MB" },
  { id: "RPT-2026-032", title: "Post-event review — Garissa floods", type: "On-demand", period: "drafting", status: "generating", size: "—" },
];

export default function ReportsPage() {
  return (
    <>
      <PageHeader
        title="Reports"
        description="Operational and analytical reports generated by the reports pipeline (analytics service + document templating)."
        action={<Button>Generate report</Button>}
      />

      <Card title="Report archive">
        <div className="overflow-x-auto">
          <table className="w-full text-left text-sm">
            <thead>
              <tr className="border-b border-slate-800 text-xs uppercase tracking-wider text-slate-500">
                <th className="py-3 pr-4">Report</th>
                <th className="py-3 pr-4">Type</th>
                <th className="py-3 pr-4">Period</th>
                <th className="py-3 pr-4">Size</th>
                <th className="py-3 pr-4">Status</th>
                <th className="py-3">Actions</th>
              </tr>
            </thead>
            <tbody>
              {REPORTS.map((r) => (
                <tr key={r.id} className="border-b border-slate-800/60 last:border-0">
                  <td className="py-3 pr-4">
                    <p className="font-medium text-slate-100">{r.title}</p>
                    <p className="font-mono text-[11px] text-slate-600">{r.id}</p>
                  </td>
                  <td className="py-3 pr-4 text-slate-300">{r.type}</td>
                  <td className="py-3 pr-4 text-slate-400">{r.period}</td>
                  <td className="py-3 pr-4 font-mono text-xs text-slate-500">{r.size}</td>
                  <td className="py-3 pr-4">
                    {r.status === "ready" && <Badge tone="success">Ready</Badge>}
                    {r.status === "generating" && <Badge tone="info">Generating</Badge>}
                    {r.status === "scheduled" && <Badge>Scheduled</Badge>}
                  </td>
                  <td className="py-3">
                    {r.status === "ready" ? (
                      <Button size="sm" variant="secondary">
                        Download PDF
                      </Button>
                    ) : (
                      <span className="text-xs text-slate-600">—</span>
                    )}
                  </td>
                </tr>
              ))}
            </tbody>
          </table>
        </div>
      </Card>

      <div className="mt-6 grid gap-4 md:grid-cols-3">
        <Card title="Scheduled outputs">
          <ul className="space-y-2 text-sm text-slate-300">
            <li>· Daily national briefing — 06:00 EAT</li>
            <li>· Weekly situational report — Mon 08:00</li>
            <li>· Model drift report — 1st of month</li>
          </ul>
        </Card>
        <Card title="Distribution">
          <p className="text-sm text-slate-300">
            Reports are emailed to authorized agency addresses and archived in Supabase Storage.
          </p>
        </Card>
        <Card title="Retention policy">
          <p className="text-sm text-slate-300">
            Daily/weekly: 12 months · Quarterly/annual: 7 years · On-demand: indefinite.
          </p>
        </Card>
      </div>
    </>
  );
}
